--
-- PostgreSQL database dump
--

\restrict CDF6s4VysGxfscyvasntTdTEHJbcrhGMEXd5aDnhTcDxGSqxMq2tgBZYuHWPXa6

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Accounts" (
    "Id" integer NOT NULL,
    "Code" character varying(20) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Type" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "ParentId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."Accounts" OWNER TO postgres;

--
-- Name: Accounts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Accounts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Accounts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "CompanyName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Icon" text NOT NULL,
    "Color" text NOT NULL,
    "Type" integer NOT NULL,
    "UserId" integer NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Contacts" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Type" integer NOT NULL,
    "TaxNumber" text,
    "TaxOffice" text,
    "Phone" text,
    "Email" text,
    "Address" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."Contacts" OWNER TO postgres;

--
-- Name: Contacts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Contacts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Contacts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Expenses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Expenses" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Expenses" OWNER TO postgres;

--
-- Name: Expenses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Expenses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Expenses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Incomes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Incomes" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Incomes" OWNER TO postgres;

--
-- Name: Incomes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Incomes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Incomes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InvoiceLines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."InvoiceLines" (
    "Id" integer NOT NULL,
    "InvoiceId" integer NOT NULL,
    "Description" text NOT NULL,
    "Quantity" numeric(18,4) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "VatRate" numeric(5,2) NOT NULL,
    "VatAmount" numeric(18,2) NOT NULL,
    "LineTotal" numeric(18,2) NOT NULL
);


ALTER TABLE public."InvoiceLines" OWNER TO postgres;

--
-- Name: InvoiceLines_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."InvoiceLines" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InvoiceLines_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Invoices" (
    "Id" integer NOT NULL,
    "InvoiceNumber" character varying(50) NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "InvoiceDate" timestamp with time zone NOT NULL,
    "DueDate" timestamp with time zone,
    "ContactId" integer NOT NULL,
    "SubTotal" numeric(18,2) NOT NULL,
    "VatTotal" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."Invoices" OWNER TO postgres;

--
-- Name: Invoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Invoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Invoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: JournalEntries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."JournalEntries" (
    "Id" integer NOT NULL,
    "EntryNumber" character varying(50) NOT NULL,
    "EntryDate" timestamp with time zone NOT NULL,
    "Description" character varying(500) NOT NULL,
    "IsPosted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."JournalEntries" OWNER TO postgres;

--
-- Name: JournalEntries_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."JournalEntries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."JournalEntries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: JournalEntryLines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."JournalEntryLines" (
    "Id" integer NOT NULL,
    "JournalEntryId" integer NOT NULL,
    "AccountId" integer NOT NULL,
    "Debit" numeric(18,2) NOT NULL,
    "Credit" numeric(18,2) NOT NULL,
    "Description" text
);


ALTER TABLE public."JournalEntryLines" OWNER TO postgres;

--
-- Name: JournalEntryLines_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."JournalEntryLines" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."JournalEntryLines_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Accounts" ("Id", "Code", "Name", "Type", "IsActive", "ParentId", "CreatedAt", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUsers" ("Id", "FullName", "CompanyName", "CreatedAt", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
4549e1ae-e0f0-4d06-ae9e-41e352e6ab2f	John Doe	Doe Inc	2026-02-28 13:59:28.675908+00	john@example.com	JOHN@EXAMPLE.COM	john@example.com	JOHN@EXAMPLE.COM	f	AQAAAAIAAYagAAAAENeoVcx/a/ccxU1HTyO/nMggJSk5gHJiLBro4Yr8Y2HwVFmbscwwA7RFAbUCaQ6NQw==	XGL2GTNPY4FGHGPMUVUZSWEI2HII2UM3	5841024a-90a3-46e4-a556-8cde68267f1d	\N	f	f	\N	t	0
25db3bf5-a3c0-4013-8cbf-fa850eda4e50	John Doe	Doe Inc	2026-02-28 14:03:28.20869+00	unique_john@example.com	UNIQUE_JOHN@EXAMPLE.COM	unique_john@example.com	UNIQUE_JOHN@EXAMPLE.COM	f	AQAAAAIAAYagAAAAEP6+6jjuzkc6349kmZboggSFN9RpEXDjrKJA4k9WQgzByqvl0goh5gSO8Zgk2wsVEQ==	JBWHCHSNVJYLBRU5HHDTHAXIHRANW4WR	8fb7e8fa-0bb3-49d9-8847-c881dff67112	\N	f	f	\N	t	0
37999663-60b7-417e-995f-ecfe4dd690ef	John Doe	Doe Inc	2026-02-28 14:06:00.139976+00	john	JOHN	john	JOHN	f	AQAAAAIAAYagAAAAEC2vOXZUrVSRBOT4hraVCpOskNGHXh0yCmQw8i+ea8cJmMleTIQtSladHGrNizH94g==	ACAAFXBXNBT4W3LLEW4JC4MWBYIBPIGM	4fec5c7a-35f9-40c6-840e-73204ad7521c	\N	f	f	\N	t	0
cacd311a-9a4d-4778-8960-833716bc9666	Test User	Test Inc	2026-02-28 14:12:03.288868+00	newtest_success_jetski@example.com	NEWTEST_SUCCESS_JETSKI@EXAMPLE.COM	newtest_success_jetski@example.com	NEWTEST_SUCCESS_JETSKI@EXAMPLE.COM	f	AQAAAAIAAYagAAAAEP32o9pob1MmAzCBQSG/xuX7XwJLlbCvy7SULvCCsKnVxslI0MKPdHjmZvRbjAApiA==	BBUTQFGRQKHVVN43ETKYNRTGBFGT36PA	5db2b5c4-0452-4213-892e-481a586674f3	\N	f	f	\N	t	0
\.


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name", "Description", "Icon", "Color", "Type", "UserId") FROM stdin;
\.


--
-- Data for Name: Contacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Contacts" ("Id", "Name", "Type", "TaxNumber", "TaxOffice", "Phone", "Email", "Address", "IsActive", "CreatedAt", "UserId") FROM stdin;
\.


--
-- Data for Name: Expenses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Expenses" ("Id", "UserId", "Amount", "Description", "Category", "Date", "CreatedAt") FROM stdin;
1	1	1800.00	Office Rent	Rent	2026-02-16 20:12:23.295429+00	2026-03-02 20:12:23.295333+00
2	1	350.00	Electricity & Water	Utilities	2026-02-18 20:12:23.295453+00	2026-03-02 20:12:23.295453+00
3	1	120.00	Fuel	Transport	2026-02-20 20:12:23.295453+00	2026-03-02 20:12:23.295453+00
4	1	450.00	Monthly Groceries	Food	2026-02-25 20:12:23.295453+00	2026-03-02 20:12:23.295453+00
5	1	200.00	Team Dinner	Entertainment	2026-02-27 20:12:23.295454+00	2026-03-02 20:12:23.295454+00
6	1	90.00	Software Subscriptions	Other	2026-03-01 20:12:23.295454+00	2026-03-02 20:12:23.295454+00
\.


--
-- Data for Name: Incomes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Incomes" ("Id", "UserId", "Amount", "Description", "Category", "Date", "CreatedAt") FROM stdin;
1	1	5500.00	March Salary	Salary	2026-02-15 20:12:23.257779+00	2026-03-02 20:12:23.257682+00
2	1	1200.00	Mobile App UI Design	Freelance	2026-02-22 20:12:23.257807+00	2026-03-02 20:12:23.257806+00
3	1	400.00	Stock Dividends	Investment	2026-02-28 20:12:23.257807+00	2026-03-02 20:12:23.257807+00
4	1	800.00	Sold Old Laptop	Other	2026-03-01 20:12:23.257808+00	2026-03-02 20:12:23.257807+00
\.


--
-- Data for Name: InvoiceLines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."InvoiceLines" ("Id", "InvoiceId", "Description", "Quantity", "UnitPrice", "VatRate", "VatAmount", "LineTotal") FROM stdin;
\.


--
-- Data for Name: Invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Invoices" ("Id", "InvoiceNumber", "Type", "Status", "InvoiceDate", "DueDate", "ContactId", "SubTotal", "VatTotal", "Total", "Description", "CreatedAt", "UserId") FROM stdin;
\.


--
-- Data for Name: JournalEntries; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."JournalEntries" ("Id", "EntryNumber", "EntryDate", "Description", "IsPosted", "CreatedAt", "UserId") FROM stdin;
\.


--
-- Data for Name: JournalEntryLines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."JournalEntryLines" ("Id", "JournalEntryId", "AccountId", "Debit", "Credit", "Description") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "PasswordHash", "CreatedAt") FROM stdin;
1	Burak Can	burakshaus4@gmail.com	$2a$11$MhgDX7pIAZJjOSnru2l0puE2FGufrT5tkyqWIrQF55tnnyuGwEE6m	2026-03-02 12:50:24.91252+00
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260226121852_InitialCreate	8.0.0
20260302114831_InitialCreate	8.0.10
20260305183140_AddCategories	8.0.10
\.


--
-- Name: Accounts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Accounts_Id_seq"', 1, false);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 1, false);


--
-- Name: Contacts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Contacts_Id_seq"', 1, false);


--
-- Name: Expenses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Expenses_Id_seq"', 6, true);


--
-- Name: Incomes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Incomes_Id_seq"', 4, true);


--
-- Name: InvoiceLines_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."InvoiceLines_Id_seq"', 1, false);


--
-- Name: Invoices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Invoices_Id_seq"', 1, false);


--
-- Name: JournalEntries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."JournalEntries_Id_seq"', 1, false);


--
-- Name: JournalEntryLines_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."JournalEntryLines_Id_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- Name: Accounts PK_Accounts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Accounts"
    ADD CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: Contacts PK_Contacts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contacts"
    ADD CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id");


--
-- Name: Expenses PK_Expenses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Expenses"
    ADD CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id");


--
-- Name: Incomes PK_Incomes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Incomes"
    ADD CONSTRAINT "PK_Incomes" PRIMARY KEY ("Id");


--
-- Name: InvoiceLines PK_InvoiceLines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."InvoiceLines"
    ADD CONSTRAINT "PK_InvoiceLines" PRIMARY KEY ("Id");


--
-- Name: Invoices PK_Invoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id");


--
-- Name: JournalEntries PK_JournalEntries; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JournalEntries"
    ADD CONSTRAINT "PK_JournalEntries" PRIMARY KEY ("Id");


--
-- Name: JournalEntryLines PK_JournalEntryLines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JournalEntryLines"
    ADD CONSTRAINT "PK_JournalEntryLines" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_Accounts_Code_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Accounts_Code_UserId" ON public."Accounts" USING btree ("Code", "UserId");


--
-- Name: IX_Accounts_ParentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Accounts_ParentId" ON public."Accounts" USING btree ("ParentId");


--
-- Name: IX_Accounts_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Accounts_UserId" ON public."Accounts" USING btree ("UserId");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Categories_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Categories_UserId" ON public."Categories" USING btree ("UserId");


--
-- Name: IX_Contacts_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Contacts_UserId" ON public."Contacts" USING btree ("UserId");


--
-- Name: IX_Expenses_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Expenses_UserId" ON public."Expenses" USING btree ("UserId");


--
-- Name: IX_Incomes_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Incomes_UserId" ON public."Incomes" USING btree ("UserId");


--
-- Name: IX_InvoiceLines_InvoiceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_InvoiceLines_InvoiceId" ON public."InvoiceLines" USING btree ("InvoiceId");


--
-- Name: IX_Invoices_ContactId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Invoices_ContactId" ON public."Invoices" USING btree ("ContactId");


--
-- Name: IX_Invoices_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Invoices_UserId" ON public."Invoices" USING btree ("UserId");


--
-- Name: IX_JournalEntries_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_JournalEntries_UserId" ON public."JournalEntries" USING btree ("UserId");


--
-- Name: IX_JournalEntryLines_AccountId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_JournalEntryLines_AccountId" ON public."JournalEntryLines" USING btree ("AccountId");


--
-- Name: IX_JournalEntryLines_JournalEntryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_JournalEntryLines_JournalEntryId" ON public."JournalEntryLines" USING btree ("JournalEntryId");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: Accounts FK_Accounts_Accounts_ParentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Accounts"
    ADD CONSTRAINT "FK_Accounts_Accounts_ParentId" FOREIGN KEY ("ParentId") REFERENCES public."Accounts"("Id");


--
-- Name: Accounts FK_Accounts_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Accounts"
    ADD CONSTRAINT "FK_Accounts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Categories FK_Categories_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "FK_Categories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Contacts FK_Contacts_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contacts"
    ADD CONSTRAINT "FK_Contacts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Expenses FK_Expenses_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Expenses"
    ADD CONSTRAINT "FK_Expenses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Incomes FK_Incomes_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Incomes"
    ADD CONSTRAINT "FK_Incomes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: InvoiceLines FK_InvoiceLines_Invoices_InvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."InvoiceLines"
    ADD CONSTRAINT "FK_InvoiceLines_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES public."Invoices"("Id") ON DELETE CASCADE;


--
-- Name: Invoices FK_Invoices_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "FK_Invoices_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Invoices FK_Invoices_Contacts_ContactId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "FK_Invoices_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES public."Contacts"("Id") ON DELETE RESTRICT;


--
-- Name: JournalEntries FK_JournalEntries_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JournalEntries"
    ADD CONSTRAINT "FK_JournalEntries_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: JournalEntryLines FK_JournalEntryLines_Accounts_AccountId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JournalEntryLines"
    ADD CONSTRAINT "FK_JournalEntryLines_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES public."Accounts"("Id") ON DELETE CASCADE;


--
-- Name: JournalEntryLines FK_JournalEntryLines_JournalEntries_JournalEntryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JournalEntryLines"
    ADD CONSTRAINT "FK_JournalEntryLines_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES public."JournalEntries"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict CDF6s4VysGxfscyvasntTdTEHJbcrhGMEXd5aDnhTcDxGSqxMq2tgBZYuHWPXa6

